library/urls.py
from django.conf.urls import url, include

from library.views import *
from rest_framework.routers import DefaultRouter


urlpatterns = [
    url(r'^author/$', AuthorList.as_view(), name='authors'),
    url(r'^book/(?P<pk>\d+)/$', BookDetail.as_view(), name='books_detail'),
    url(r'^add_book/$', AddBook.as_view(), name='add_book'),
    url(r'^add_author/$', AddAuthor.as_view(), name='add_author'),
    url(r'^$', FindBook.as_view(), name='books'),
    url(r'^author_books/$', AuthorBooks.as_view(), name='author_books'),
    # url(r'^test/$', test_ang, name='test'),
    url(r'^library/$', api_authors, name='test'),
]

router = DefaultRouter()
router.register(r'authors', APIAuthorViewSet)
router.register(r'books', APIBookViewSet)

urlpatterns += [
    url(r'^api/', include(router.urls), name='api'),
]

# urlpatterns += [
#    url(r'^api-author-list/$', APIAuthorList.as_view(), name='APIauthorList'),
#     url(r'^api-book-list/$', APIBookList.as_view(), name='APIbookList'),
#     url(r'^api-book-detail/(?P<pk>[0-9]+)/$', APIBookDetail.as_view()),
# ]

testCBV/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('library.urls', namespace='library')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

library/models.py
from __future__ import unicode_literals

from django.db import models


class TabsMenu(models.Model):
    name_tabs = models.CharField(max_length=20)
    link_tabs = models.CharField(max_length=200)
    label_tabs = models.CharField(max_length=200)

    def __unicode__(self):
        return ''.join([self.name_tabs])


class Author(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)

    def __unicode__(self):
        return ''.join([self.first_name, self.last_name])


class User(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)

    def __unicode__(self):
        return ''.join([self.first_name, self.last_name])


class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(Author)
    user_now = models.ForeignKey(User, blank=True, null=True)
    user_before = models.ManyToManyField(User,
                                         related_name='ex_user', blank=True)
    date = models.DateField(blank=True, null=True)

    def __unicode__(self):
        return self.title

library/forms.py
from django import forms

from library.models import Book, Author


class AddBookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(AddBookForm, self).__init__(*args, **kwargs)
        # self.fields['author'].widget.attrs.update({'class': 'form-control'})
        for key, field in self.fields.iteritems():
            field.widget.attrs.update({'class': 'form-control'})


class AddAuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(AddAuthorForm, self).__init__(*args, **kwargs)
        for key, field in self.fields.iteritems():
            field.widget.attrs.update({'class': 'form-control'})

library/views.py
# -*- coding: utf-8 -*-
from django.contrib.messages.views import SuccessMessageMixin
from django.core.urlresolvers import reverse_lazy, reverse
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView
import datetime
from library.models import *
from library.forms import *
from library.serializers import AuthorSerializer, BooksSerializer
from rest_framework import viewsets
# from rest_framework.generics import ListAPIView, RetrieveAPIView


class Tabs(object):
    active_tab = None

    def get_context_data(self, **kwargs):
        context = super(Tabs, self).get_context_data()
        context['active'] = self.active_tab
        context['tabs'] = TabsMenu.objects.all()
        return context


class AuthorList(Tabs, ListView):
    model = Author
    template_name = 'library/author_list.html'
    active_tab = 'authors'


class BookDetail(Tabs, DetailView):
    model = Book
    template_name = 'library/book_detail.html'
    context_object_name = 'book'


class AddBook(SuccessMessageMixin, Tabs, CreateView):
    model = Book
    # fields = ['title', 'author', 'user_now', 'user_before']
    template_name = 'library/book_create_form.html'
    success_url = reverse_lazy('library:books')
    form_class = AddBookForm
    active_tab = 'add_book'
    success_message = 'add book success!'


class AddAuthor(Tabs, CreateView):
    model = Author
    # fields = ['first_name', 'last_name']
    template_name = 'library/author_create_form.html'
    success_url = reverse_lazy('library:authors')
    form_class = AddAuthorForm
    active_tab = 'add_author'

    def get_context_data(self, **kwargs):
        context = super(AddAuthor, self).get_context_data()
        context['next'] = self.request.GET.get('next')
        return context

    def get_success_url(self):
        next_url = self.request.POST.get('next')
        if next_url:
            return next_url
        else:
            return reverse('library:books')


class FindBook(Tabs, ListView):
    model = Book
    template_name = 'library/book_list.html'
    active_tab = 'find_book'

    def get_context_data(self, **kwargs):
        context = super(FindBook, self).get_context_data(**kwargs)
        context['authors'] = Author.objects.all()
        context['search'] = self.request.GET.get('find')
        context['begin_date'] = self.request.GET.get('date1')
        context['end_date'] = self.request.GET.get('date2')
        try:
            context['sel_author'] = int(self.request.GET.get('select_author'))
        except (ValueError, TypeError):
            context['sel_author'] = ''
        return context

    def get_queryset(self):
        query = super(FindBook, self).get_queryset()
        title = self.request.GET.get('find')

        if title:
            query = query.filter(title__icontains=title)
        author = self.request.GET.get('select_author')
        if author:
            query = query.filter(author_id=author)
        begin_date = self.request.GET.get('start')
        end_date = self.request.GET.get('end')
        if self.validate_date(begin_date):
            query = query.filter(date__gte=begin_date)
        if self.validate_date(end_date):
            query = query.filter(date__lte=end_date)
        sort_query = self.request.GET.get('sorted')
        if sort_query:
            query = query.order_by(sort_query)
        return query

    @staticmethod
    def validate_date(date):
        try:
            datetime.datetime.strptime(date, "%Y-%m-%d")
        except (TypeError, ValueError):
            return False
        return True


class AuthorBooks(Tabs, ListView):
    model = Book
    template_name = 'library/author_books_ajax.html'

    def get_queryset(self):
        query = super(AuthorBooks, self).get_queryset()
        author = self.request.GET.get('select_author')
        if author:
            query = Book.objects.filter(author=author)
        return query


class APIAuthorViewSet(viewsets.ModelViewSet):
    queryset = Author.objects.all()
    serializer_class = AuthorSerializer


class APIBookViewSet(viewsets.ModelViewSet):
    queryset = Book.objects.all()
    serializer_class = BooksSerializer


def api_authors(request):

    return render(request, 'library/angular_view.html')

library/templates/library/angular_view.html
{% extends 'library/base.html' %}

{% block content %}

    <div ng-view></div>

{% endblock %}

library/templates/library/author_book_list.html
{% extends 'library/base.html' %}
{% block title %} Книги автора {% endblock %}

{% block content %}
    <a href="/">Главная</a>
    {% for book in books %}
        <div class="row">
           <div class="col-sm-4">
               <ul class="list-group">
                   <a href="{% url 'library:books_detail' book.id %}">
                       <li class="list-group-item">
                           {{ book.title }}
                       </li>
                   </a>
               </ul>
           </div>
        </div>
    {% endfor %}
{% endblock %}

library/templates/library/author_books_ajax.html
<table class="table table-striped">
    <tr>
        <th>Название</th>
        <th>Дата</th>
        <th></th>
    </tr>
    {% for book in object_list %}
        <tr>
            <td>{{ book.title }}</td>
            <td>{% if book.date %}{{ book.date }}{% endif %}</td>
            <td>
                <a class="btn btn-default" href="{% url "library:books_detail" book.id %}">
                Detail</a>
            </td>
        </tr>
    {% endfor %}
</table>



{#<div class="popover-content">#}
{#        {% for book in object_list %}#}
{#            <div class="row">#}
{#                <div class="col-sm-8">#}
{#                    <ul class="list-group">#}
{#                        <li class="list-group-item">#}
{#                            <div>#}
{#                                <label>Title:</label> {{ book.title }}#}
{#                            </div>#}
{#                            <div>#}
{#                                <label>Author:</label> {{ book.author.last_name }}#}
{#                                 {{ book.author.first_name }}#}
{#                            </div>#}
{#                            <div>#}
{#                                <label>Date</label> {{ book.date }}#}
{#                            </div>#}
{#                            <a class="btn btn-default" href="{% url "library:books_detail" book.id %}">Detail</a>#}
{#                        </li>#}
{#                    </ul>#}
{#                </div>#}
{#            </div>#}
{#        {% endfor %}#}
{#    </div>#}

library/templates/library/author_create_form.html
{% extends 'library/base.html' %}
{% block title %} {% endblock %}

{% block content %}

    <form class="form-horizontal" action="{% url 'library:add_author' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}" />
        {% for field in form %}
            {% with errors=field.errors %}
                <div class="form-group {% if errors %} has-error{% endif %}" >
                    <div class=" col-sm-6">
                        {{ field.label_tag }} {{ field }}

                    </div>
                    {% include 'library/if_errors.html' %}
                </div>
            {% endwith %}
        {% endfor %}
        <input class="btn btn-primary btn-lg active" type="submit" value="Save"/>
    </form>
{% endblock %}

library/templates/library/author_list.html
{% extends 'library/base.html' %}
{% block title %}{% endblock %}

{% block content %}
<script type="text/javascript">
    var author_id = "{{ request.GET.author_id }}";
</script>
    <div class="container">
        <div class="col-md-6">
            <h2>Авторы</h2>
            <table class="table table-striped">
                <tr>
                    <th>Имя</th>
                    <th>Фамилия</th>
                    <th>Книг написал</th>
                    <th>Список книг</th>
                </tr>
                {% for author in object_list %}
                    <tr>
                        <td>{{ author.first_name }}</td>
                        <td>{{ author.last_name }}</td>
                        <td>{{ author.book_set.count }}</td>
                        <td><button class="btn btn-default books_author" data-authorid="{{ author.id }}"
                                                name="select_author">Книги автора</button>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
        <div class="col-md-6">
            <div id="content"></div>
        </div>
    </div>


{% endblock %}

library/templates/library/base.html
<!DOCTYPE html>
<html lang="en" ng-app="library">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {%load staticfiles%}
    <script type="text/javascript" src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'lib/bootstrap.js' %}"></script>
    <script type="text/javascript" src="{% static 'lib/angular.min.js' %}"></script>

    <script type="text/javascript" src="{% static 'lib/main.js' %}"></script>
    <script type="text/javascript" src="{% static 'lib/ui-bootstrap-tpls-1.3.3.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'bower_components/angular-route/angular-route.js' %}"></script>
    <script type="text/javascript" src="{% static 'bower_components/angular-resource/angular-resource.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'bower_components/moment/min/moment.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'bower_components/datepicker/js/bootstrap-datepicker.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'library/main.js' %}"></script>
    <script type="text/javascript" src="{% static 'library/ajax.js' %}"></script>
    <script type="text/javascript" src="{% static 'library/csrf.js' %}"></script>
    <script type="text/javascript" src="{% static 'library/popup.js' %}"></script>
    <script type="text/javascript" src="{% static 'library/controller/ang_api.js' %}"></script>


    <link href="{% static 'lib/bootstrap.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'bower_components/datepicker/css/bootstrap-datepicker.min.css' %}" />
    <link rel="stylesheet" href="{% static 'lib/bootstrap.css' %}" />
</head>
<body>
    {% csrf_token %}
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed"
            data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
                aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
            </button>

            <a class="navbar-brand" href="{% url 'library:books' %}">Brand</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown"
                       role="button" aria-haspopup="true"
                       aria-expanded="false">MENU <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        {% if tabs %}
                            {% for tab in tabs %}
                                <li role="presentation" class="{% if active == tab.label_tabs %} active {% endif %}">
                                    <a href="{% url tab.link_tabs %}"> {{ tab }}</a>
                                </li>
                            {% endfor %}
                        {% else %}
                            <li role="presentation" {% if url == '/author/' %} class="active"{% endif %}><a href="#/authors">Authors</a></li>
                            <li role="presentation" {% if url == '/' %} class="active"{% endif %}><a href="#/books">Books</a></li>
                            <li role="presentation" {% if url == '/add_book/' %} class="active"{% endif %}><a href="#/add-book">Add Book</a></li>
                            <li role="presentation" {% if url == '/add_author/' %} class="active"{% endif %}><a href="#/add-author">Add Author</a></li>
                        {% endif %}
                    </ul>
                </li>
            </ul>
            <form class="navbar-form navbar-left" role="search"
                  action="{% url 'library:books' %}" method="get">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Поиск Книг" name="find">
                </div>
                <button type="submit" class="btn btn-default">Найти</button>
            </form>
        </div>

    </div>
</nav>
{% block content %} {% endblock %}
    <div class="footer">

    </div>

</body>
</html>

library/templates/library/book_create_form.html
{% extends 'library/base.html' %}
{% block title %} {% endblock %}

{% block content %}
    <div>
        <div class="">
            <form class="form-horizontal" action="{% url 'library:add_book'%}" method="post">
                {% csrf_token %}
                {% for field in form %}
                    {% with errors=field.errors %}
                        <div class="form-group {% if errors %} has-error{% endif %}" >
                            {% if field.name == "author" %}
                                    <div class="col-xs-5">
                                        <div class="input-group">
                                            {{ field }}
                                            <span class="input-group-btn">
                                                <a class="btn  btn-default" href="{% url "library:add_author" %}?next={{ request.path }}">Add</a>
                                            </span>
                                        </div>
                                    </div>
                            {% elif field.name == "date" %}
                                    {% include 'library/date.html' %}
                            {% else %}
                                <div class="col-xs-5">
                                    {{ field.label_tag }} {{ field }}
                                </div>
                                {% include 'library/if_errors.html' %}
                            {% endif %}
                        </div>
                    {% endwith %}
                {% endfor %}
            {% if messages %}
{% endif %}
                <div class="container">
                    <button class="btn btn-primary btn-lg active" type="submit">Save</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

library/templates/library/book_detail.html
{% extends 'library/base.html' %}

{% block title %}{{ book.title }}{% endblock %}
{% block content %}
    <div class="container">
        <ul class="list-unstyled">
            <h3>{{ book.title }}</h3>
            <li> <label>Author:</label> {{ book.author.last_name }}
            {{ book.author.first_name }}</li>
            <li><label>Date:</label> {{ book.date }}</li>
            {% if book.user_now %}
                <li><label>Книга находится у:</label>
                    {{ book.user_now }} {{ book.user_now.first_name }}</li>
            {% endif %}
            {% if book.user_before.exists %}
                <li><label>Книга находилась у: </label>{{ book.user_before.all }}</li>
            {% endif %}
        </ul>
    </div>

{% endblock %}

library/templates/library/book_list.html
{% extends 'library/base.html' %}
{% block title %} {% endblock %}

{% block content %}
    {% if messages %}
        {% include 'library/popup.html' %}
    {% endif %}
    <div class="container-fluid">
        <div class="container">
            <form class="form-horizontal" action="{% url 'library:books' %}" method="get">
                <div class="col-md-10">
                    <div class="col-md-9">
                    <h2>Поиск</h2>
                        <div class="form-group">
                            <div class="col-lg-6">
                                <input class="form-control" type="text" name="find" placeholder="Поиск по названию"
                                       value="{% if search %}{{ search }}{% endif %}">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-lg-6">
                                Выбрать автора:
                                <select name="select_author" class="form-control">
                                    <option value="">---------</option>
                                    {% for author in authors %}
                                        <option value="{{ author.id }}" {% if author.id == sel_author %}selected="selected"{% endif %}>
                                            {{ author.first_name }} {{ author.last_name }}
                                        </option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class='col-lg-6'>
                                <div id="sandbox-container">
                                    <div class="input-daterange input-group" id="datepicker">
                                        <input type="text" class="input-sm form-control" name="start" />
                                        <span class="input-group-addon">to</span>
                                        <input type="text" class="input-sm form-control" name="end" />
                                    </div>
                                </div>
                            </div>
                        </div>
                        <input class="btn btn-default" type="submit" value="Find">
                    </div>
                </div>
                <div class="col-md-2">
                    <h4>Сортировать:</h4>
                    <div class="form-group">
                        <div class="col-sm-12">
                            <select name="sorted" class="form-control">
                                <option value="author">Автор</option>
                                <option value="date">Дате</option>
                                <option value="title">Названию</option>
                            </select>
                        </div>
                    </div>
                </div>
            </form>
        </div>

        <div class="container">
            <div class="container">
                <div class="col-sm-12">
                    <table class="table table-striped">
                        <tr>
                            <th><label>Title:</label></th>
                            <th><label>Author:</label></th>
                            <th><label>Date</label></th>
                        </tr>
                        {% for book in object_list %}
                            <tr>
                                <td><a href="{% url "library:books_detail" book.id %}">{{ book.title }}</a></td>
                                <td>
                                    <a href="{% url "library:authors"%}?author_id={{ book.author.id }}" >
                                        {{ book.author.last_name }} {{ book.author.first_name }}
                                    </a>
                                </td>
                                <td> {% if book.date %} {{ book.date }} {% endif %}</td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

library/templates/library/date.html
        <div class='col-xs-5'>
            {{ field.label_tag }}
                <div class='input-group date' id='datetimepicker1'>
                    {{ field }}
                    {% include 'library/if_errors.html' %}
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
            <div class="input-daterange input-group" id="datepicker">
                <input type="text" class="input-sm form-control" name="start" />
                <span class="input-group-addon">to</span>
                <input type="text" class="input-sm form-control" name="end" />
            </div>
        </div>

library/templates/library/if_errors.html
{% if errors %}
    {% for error in errors %}
        <span class="help-block">{{ error }}</span>
    {% endfor %}
{% endif %}

library/templates/library/index.html
{% extends 'library/base.html' %}2
{% block title %} Главная {% endblock %}
{% block content %}
        <ul class="nav nav-pills" role="tablist">
            <li role="presentation"><a href="{% url 'library:authors' %}">Authors</a></li>
            <li role="presentation"><a href="{% url 'library:books' %}">Books</a></li>
            <li role="presentation"><a href="{% url 'library:add_book' %}">Add Book</a></li>
            <li role="presentation"><a href="{% url 'library:add_author' %}">Add Author</a></li>
        </ul>
{% endblock %}

library/templates/library/popup.html
    <div id="popup" class="alert alert-warning alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </div>